INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (1, 'Valorant PUGS', 'Valorant Game Night! Open to all skill levels for some fun casual games', 'https://i.guim.co.uk/img/media/9c25f338317ac9a237e43e7356fe615fbb22d2af/2421_521_6134_3685/master/6134.jpg?width=465&quality=45&auto=format&fit=max&dpr=2&s=0733ab46c77ec44265280d34d31a20d4', 'Video Game', 'Valorant');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (2, 'Catan fun', 'Start your settlement with us!', 'https://www.reviewgeek.com/p/uploads/2021/06/a0d6f24b.png?width=1200', 'Board Game', 'Catan');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (3, 'LFG Risk of Rain 2', 'Looking to play with 3 others in risk of rain!', 'https://assets.nintendo.com/image/upload/ar_16:9,b_auto,c_pad,dpr_3.0,f_auto,q_auto,w_500/b_rgb:ffffff/v1/ncom/en_US/games/switch/r/risk-of-rain-2-switch/hero', 'Video Game', 'Risk of Rain 2');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (4, 'Only +4s', 'Destroy possible friendships playing Uno :)', 'https://i.insider.com/5cd062dcf067174d3f7c4d71?width=1200&format=jpeg', 'Card Game', 'Uno');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'Raid Night', 't3 Abyss dungeon is waiting for you', 'https://images.ctfassets.net/umhrp0op95v1/3uKxpqws73m0VRKwmOk3WA/2c14d34e4080b0d226d002bc2cccade6/Lost_Ark_Key_Art_1200x630.jpg', 'Video Game', 'Lost Ark');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'League of Legends LFG Flex Ranks', 'Looking for flex group for flex rank Diamond, I can play top/adc or mid', 'https://staticg.sportskeeda.com/editor/2021/01/dffdc-16120717956166-800.jpg', 'Video Game', 'League of Legends');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (1, 'CS GO surf race', 'Feel free to join our surf race server', 'https://cdn.mos.cms.futurecdn.net/ZPwx6tmYKQtnPZDRCAfXMj.jpg', 'Video Game', 'Counter-Strike: Global Offensive');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (1, 'LFG for Destiny 2 Vow of the Disciple raid', 'Need a group for the new raid', 'https://destiny.wiki.gallery/images/thumb/0/0e/Vow_of_the_Disciple.jpg/1600px-Vow_of_the_Disciple.jpg', 'Video Game', 'Destiny 2');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (1, 'Cards Against Humanity only wrong answers', 'Come join us and remember only wrong answers are the right answers', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Cards_Against_Humanity_logo_2009.svg/800px-Cards_Against_Humanity_logo_2009.svg.png', 'Card Game', 'Cards Against Humanity');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (2, 'Magic: the Gathering Pauper games', 'Come join in some pauper games all are welcomed', 'https://imageio.forbes.com/blogs-images/laurenorsini/files/2019/06/EN_PauperFormat_Header-1200x700.jpg?format=jpg&width=1200&fit=bounds', 'Card Game', 'Magic: The Gathering');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'Come play Civilization 6', 'Rise to the top and conquer join us in a fun game of Civilization 6', 'https://cdn.vox-cdn.com/thumbor/ezO6Tuib470ku37q9HPSnopKAwE=/0x0:1158x651/1200x800/filters:focal(487x234:671x418)/cdn.vox-cdn.com/uploads/chorus_image/image/66827138/civ6.0.0.png', 'Video Game', 'Civilization VI');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (2, 'Party at home with Jackbox Party Pack 3', 'Looking for others to play The Jackbox Party Pack 3 with', 'https://cdn.akamai.steamstatic.com/steam/apps/434170/capsule_616x353.jpg?t=1597699274', 'Video Game', 'Jack Box Party Pack');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (4, 'Storm Kings thunder', 'DM looking for an unruly bunch to start an adventure with', 'https://www.tribality.com/wp-content/uploads/2016/09/STK_Thumbnail.jpg', 'Role-playing Game', 'Dungeons & Dragons');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'Tales from the Yawning Portal dungeon crawl!', 'Looking for a group to traverse through dunegons with', 'https://www.tribality.com/wp-content/uploads/2017/01/Tales-from-the-Yawning-Portal-800x400.jpg', 'Role-playing Game', 'Dungeons & Dragons');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'Chess noob looking to learn!', 'Just started playing chess and would love to play with any one and tips would be appreciated', 'https://assets.dicebreaker.com/chess-playing-hand.jpeg/BROK/thumbnail/1600x900/quality/100/chess-playing-hand.jpeg', 'Board Game', 'Chess');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'LFG Argos Raid', 'Looking for a group to play the raid tonight I have a 1400 Berserker ready to go', 'https://images.ctfassets.net/umhrp0op95v1/729b92nLAFMighCKqGScpf/463782b9c34ae4dfb25c308e2fb2aeef/LA_Argos_Concept_01_740x416.jpg', 'Video Game', 'Lost Ark');
INSERT INTO appointments (host_id, title, description, image, category, game) VALUES (5, 'Need a duo for Diamond ranks', 'Looking for a duo partner in ranks my schedule is usually at around 3 PM EST - 7 PM EST', 'https://cdn1.epicgames.com/offer/cbd5b3d310a54b12bf3fe8c41994174f/EGS_VALORANT_RiotGames_S1_2560x1440-160cacc798ef1693cc0a339e869f1761', 'Video Game', 'Valorant');


