INSERT INTO games (name, image, category_id) VALUES ('Lost Ark', 'https://images.ctfassets.net/umhrp0op95v1/3uKxpqws73m0VRKwmOk3WA/2c14d34e4080b0d226d002bc2cccade6/Lost_Ark_Key_Art_1200x630.jpg', 1);
INSERT INTO games (name, image, category_id) VALUES ('Valorant', 'https://stanforddaily.com/wp-content/uploads/2020/08/image-2.png', 1);
INSERT INTO games (name, image, category_id) VALUES ('Risk of Rain 2', 'https://upload.wikimedia.org/wikipedia/en/c/c1/Risk_of_Rain_2.jpg', 1);
INSERT INTO games (name, image, category_id) VALUES ('Uno', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/UNO_Logo.svg/1200px-UNO_Logo.svg.png', 2);
INSERT INTO games (name, image, category_id) VALUES ('Catan', 'https://upload.wikimedia.org/wikipedia/en/a/a3/Catan-2015-boxart.jpg', 3);
INSERT INTO games (name, image, category_id) VALUES ('League of Legends', 'https://staticg.sportskeeda.com/editor/2021/01/dffdc-16120717956166-800.jpg', 1);
INSERT INTO games (name, image, category_id) VALUES ('Counter-Strike: Global Offensive', 'https://cdn.mos.cms.futurecdn.net/ZPwx6tmYKQtnPZDRCAfXMj.jpg', 1);
INSERT INTO games (name, image, category_id) VALUES ('Destiny 2', 'https://destiny.wiki.gallery/images/thumb/0/0e/Vow_of_the_Disciple.jpg/1600px-Vow_of_the_Disciple.jpg', 1);
INSERT INTO games (name, image, category_id) VALUES ('Cards Against Humanity', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Cards_Against_Humanity_logo_2009.svg/800px-Cards_Against_Humanity_logo_2009.svg.png', 2);
INSERT INTO games (name, image, category_id) VALUES ('Magic: the Gathering',  'https://imageio.forbes.com/blogs-images/laurenorsini/files/2019/06/EN_PauperFormat_Header-1200x700.jpg?format=jpg&width=1200&fit=bounds', 2);
INSERT INTO games (name, image, category_id) VALUES ('Civilization VI', 'https://cdn.vox-cdn.com/thumbor/ezO6Tuib470ku37q9HPSnopKAwE=/0x0:1158x651/1200x800/filters:focal(487x234:671x418)/cdn.vox-cdn.com/uploads/chorus_image/image/66827138/civ6.0.0.png', 1);
INSERT INTO games (name, image, category_id) VALUES ('Jack Box Party Pack', 'https://cdn.akamai.steamstatic.com/steam/apps/434170/capsule_616x353.jpg?t=1597699274', 1);
INSERT INTO games (name, image, category_id) VALUES ('Dungeons & Dragons', 'https://www.tribality.com/wp-content/uploads/2016/09/STK_Thumbnail.jpg', 4);
INSERT INTO games (name, image, category_id) VALUES ('Chess', 'https://assets.dicebreaker.com/chess-playing-hand.jpeg/BROK/thumbnail/1600x900/quality/100/chess-playing-hand.jpeg', 3);